Repository QASTUDIODEV/WEB_QASTUDIO, pull requests merged in 2025-02, with the labels that each got.

#180 ✨ [Feature] 표 api 검색/달력 연결
  src/components/dashboard/calendar/calendar.tsx
  src/components/dashboard/table/pageNameHeader.tsx
  src/components/dashboard/table/table.style.ts
  src/components/dashboard/table/table.tsx
  src/pages/dashboard/dashboard.style.ts
  src/pages/dashboard/dashboard.tsx
  src/slices/calendarSlice.ts
  src/types/test/test.ts
Labels: ✨ Feature

#185 [Feature/#184] 1차 통합 테스트 피드백 수정
  src/apis/axiosInstance.ts
  src/components/auth/authModal/authModal.style.ts
  src/components/auth/authModal/authModal.tsx
  src/components/common/modalProvider/modalProvider.tsx
  src/hooks/auth/useAuthModal.ts
  src/pages/login/login.style.ts
Labels: ✨ Feature

#187 ✨ [Feature] 로딩 컴포넌트 투명도 조절
  src/components/common/loading/loading.style.ts
Labels: ✨ Feature

#189 ✨ [Feature/#188] 1차 통합 테스트 피드백 UI 수정
  src/components/scenario/dropDown/dropDown.style.ts
  src/components/scenario/scenarioModal/scenarioModal.style.ts
Labels: ✨ Feature

#191 [bug] fix: 에러 해결
  src/apis/axiosInstance.ts
Labels: 🐞 BugFix

#195 [Bug] 로그인 실패시 모달이 뜨는 에러
  src/apis/axiosInstance.ts
Labels: 🐞 BugFix

#197 [Deploy] Deploy
  src/apis/axiosInstance.ts
  src/components/auth/authModal/authModal.style.ts
  src/components/auth/authModal/authModal.tsx
  src/components/common/loading/loading.style.ts
  src/components/common/modalProvider/modalProvider.tsx
  src/components/scenario/dropDown/dropDown.style.ts
  src/components/scenario/scenarioModal/scenarioModal.style.ts
  src/hooks/auth/useAuthModal.ts
  src/pages/login/login.style.ts
  src/pages/scenario/scenario.style.ts
Labels: 🌏 Deploy

#202 ⚙️ [Setting] pnpm 관련 빌드 오류 수정
  .github/workflows/ci.yaml
Labels: 🌏 Deploy, ⚙️ Setting

#200 ✨ [Feature] 표 Header page api 연결
  src/components/dashboard/table/pageNameHeader.tsx
  src/components/dashboard/table/table.tsx
  src/types/test/test.ts
Labels: ✨ Feature

#204 [Bug/#203] input박스 밖을 클릭 하지 않아도 검사 되도록 수정
  src/components/auth/module/module.style.ts
  src/components/auth/module/module.tsx
  src/components/findingPassword/findingPasswordStep1.tsx
  src/components/findingPassword/findingPasswordStep2.tsx
  src/components/mypage/myProfile/myProfile.tsx
  src/pages/findingPassword/findingPassword.tsx
  src/pages/login/login.tsx
  src/pages/signup/signup.tsx
  src/pages/userSetting/userSetting.tsx
Labels: 🐞 BugFix

#206 fix: disable 처리
  src/components/auth/module/module.tsx
  src/components/findingPassword/findingPasswordStep1.tsx
  src/pages/findingPassword/findingPassword.tsx
  src/pages/signup/signup.tsx
Labels: 🐞 BugFix

#199 [Feature/#193] 시나리오 조회 api 연결
  .github/workflows/ci.yaml
  src/apis/axiosInstance.ts
  src/apis/mypage/mypage.ts
  src/apis/scenario/scenario.ts
  src/components/common/modal/modal.tsx
  src/components/common/projectTitle/projectTitle.tsx
  src/components/mypage/project/project.tsx
  src/components/mypage/projectList/projectList.tsx
  src/components/scenario/buttonGroup/buttonGroup.style.ts
  src/components/scenario/buttonGroup/buttonGroup.tsx
  src/components/scenario/characterHeader/characterHeader.style.ts
  src/components/scenario/characterHeader/characterHeader.tsx
  src/components/scenario/characterList/characterList.tsx
  src/components/scenario/checkBox/checkBox.tsx
  src/components/scenario/dropDown/dropDown.tsx
  src/components/scenario/scenarioItem/scenarioItem.style.ts
  src/components/scenario/scenarioItem/scenarioItem.tsx
  src/components/scenario/scenarioModal/scenarioModal.style.ts
  src/components/scenario/scenarioModal/scenarioModal.tsx
  src/components/userInfo/otherUserProjectList/otherUserProjectList.tsx
  src/constants/querykeys/queryKeys.ts
  src/hooks/common/useAIcustonQuery.ts
  src/hooks/common/useClickOutside.ts
  src/hooks/scenario/useChangeScenarioInfo.ts.ts
  src/hooks/scenario/useGetScenarioInfo.ts
  src/pages/scenario/scenario.style.ts
  src/pages/scenario/scenario.tsx
  src/slices/scenarioSlice.ts
  src/types/scenario/scenario.ts
  src/types/userController/userController.ts
  src/utils/getPageNumbers.ts
  src/utils/transformDate.ts
  src/utils/validate.ts
Labels: ✨ Feature

#209 [bug] height 수정
  src/pages/scenario/scenario.style.ts
Labels: 🐞 BugFix

#192 ✨ [Feature/#139] 시나리오 실행 api 연결(조회)
  src/apis/scenarioAct/scenarioAct.ts
  src/components/scenarioAct/actSection/actSection.style.ts
  src/components/scenarioAct/actSection/actSection.tsx
  src/components/scenarioAct/actionItem/actionItem.tsx
  src/components/scenarioAct/characterSelectDropdown/characterSelectDropdown.style.ts
  src/components/scenarioAct/characterSelectDropdown/characterSelectDropdown.tsx
  src/components/scenarioAct/controller/controller.style.ts
  src/components/scenarioAct/controller/controller.tsx
  src/components/scenarioAct/header/header.style.ts
  src/components/scenarioAct/header/header.tsx
  src/components/scenarioAct/scenarioItem/scenarioItem.tsx
  src/components/scenarioAct/selectDropdown/selectDropdown.tsx
  src/constants/querykeys/queryKeys.ts
  src/hooks/scenarioAct/useProjectInfo.ts
  src/hooks/scenarioAct/useScenarioList.ts
  src/pages/scenarioAct/scenarioAct.style.ts
  src/pages/scenarioAct/scenarioAct.tsx
  src/slices/scenarioActSlice.ts
  src/types/scenarioAct/scenarioAct.ts
Labels: ✨ Feature

#214 [Bug/#213] route 오류 수정
  src/pages/addProject/addProject.tsx
Labels: 🐞 BugFix

#216 [Feature/#215] 팀원 마이페이지 연결 및 스타일 수정
  src/pages/projectInfo/projectInfo.style.ts
  src/pages/projectInfo/projectInfo.tsx
  src/pages/projectInfo/projectStructure.style.ts
  src/pages/projectInfo/projectStructure.tsx
Labels: ✨ Feature

#220 ✨ [Feature] 공용 not-found
  src/pages/error/error.style.ts
  src/pages/error/error.tsx
  src/routes/index.tsx
  src/styles/theme.ts
Labels: ✨ Feature

#219 [Refactor/#211] 시나리오 조회 리팩토링
  src/components/common/modal/modal.style.ts
  src/components/projectInfo/dropDown/dropDown.style.ts
  src/components/scenario/buttonGroup/buttonGroup.tsx
  src/components/scenario/characterHeader/characterHeader.style.ts
  src/components/scenario/characterHeader/characterHeader.tsx
  src/components/scenario/scenarioItem/scenarioItem.style.ts
  src/components/scenario/scenarioItem/scenarioItem.tsx
  src/components/scenario/scenarioModal/scenarioModal.tsx
  src/components/scenario/scenarioModal/scenarioModal/scenarioModalStep.style.ts
  src/components/scenario/scenarioModal/scenarioModal/scenarioModalStep1.tsx
  src/components/scenario/scenarioModal/scenarioModal/scenarioModalStep2.tsx
  src/pages/scenario/scenario.tsx
  src/utils/getPageNumbers.ts
  src/utils/validate.ts
Labels: ♻️ Refactor

#222 ♻️ [Refactor] modal 수정
  src/components/common/modal/modal.tsx
  src/components/scenario/scenarioModal/scenarioModal.tsx
Labels: ♻️ Refactor

#223 [Refactor/#210] 마이페이지 리팩토링
  src/apis/images/images.ts
  src/components/mypage/myProfile/MyProfile.style.ts
  src/components/mypage/myProfile/myProfile.tsx
  src/components/mypage/projectList/projectList.tsx
  src/components/mypage/projectNum/projectNum.tsx
  src/pages/mypage/mypage.style.ts
  src/pages/mypage/mypage.tsx
  src/utils/santizeFilename.ts
Labels: ♻️ Refactor

#224 [Refactor/#212] auth 리팩토링
  src/assets/icons/check_circle_pri50.svg
  src/assets/icons/spin.svg
  src/components/auth/module/module.style.ts
  src/components/auth/module/module.tsx
  src/components/common/loading/loadingSpinner.style.ts
  src/components/common/loading/loadingSpinner.tsx
  src/components/findingPassword/findingPasswordStep1.tsx
  src/pages/findingPassword/findingPassword.tsx
  src/pages/signup/signup.tsx
Labels: ♻️ Refactor

#228 [Bugfix] 배너 이미지 클릭 시 input이 잘 열리도록 수정
  src/components/mypage/myProfile/MyProfile.style.ts
  src/components/mypage/myProfile/myProfile.tsx
Labels: 🐞 BugFix

#229 [Refactor/#207] sidebar 컴포넌트 분리 및 코드 오류 수정
  src/components/common/modalProvider/modalProvider.tsx
  src/components/common/sidebar/ProjectItem.tsx
  src/components/common/sidebar/logtoutModal/logoutModal.tsx
  src/components/common/sidebar/profile/sideBarProfile.style.ts
  src/components/common/sidebar/profile/sideBarProfile.tsx
  src/components/common/sidebar/projectItem/ProjectItem.tsx
  src/components/common/sidebar/projectItem/projectItem.style.ts
  src/components/common/sidebar/projectList/projectList.style.ts
  src/components/common/sidebar/projectList/projectList.tsx
  src/components/common/sidebar/projectModal/projectModal.tsx
  src/components/common/sidebar/projectProfile/projectProfile.style.ts
  src/components/common/sidebar/projectProfile/projectProfile.tsx
  src/components/common/sidebar/sidebar.style.ts
  src/components/common/sidebar/sidebar.tsx
  src/pages/addProject/addProject.tsx
  src/routes/index.tsx
  src/types/sidebar/sidebar.ts
Labels: ♻️ Refactor

#231 [Refactor/#225] information 페이지 리팩토링 및 피드백 반영
  src/components/common/modalProvider/modalProvider.tsx
  src/components/common/sidebar/projectModal/projectModal.tsx
  src/components/projectInfo/characterBox/characterBox.style.ts
  src/components/projectInfo/characterBox/characterBox.tsx
  src/components/projectInfo/characterModal/characterModal.style.ts
  src/components/projectInfo/characterModal/characterModal.tsx
  src/components/projectInfo/inviteModal/inviteModal.style.ts
  src/components/projectInfo/inviteModal/inviteModal.tsx
  src/components/projectInfo/pageModal/pageModal.tsx
  src/components/projectInfo/projectInput/projectInput.style.ts
  src/components/projectInfo/projectInput/projectInput.tsx
  src/components/projectInfo/projectIntroduction/projectIntro.style.ts
  src/components/projectInfo/projectIntroduction/projectIntro.tsx
  src/components/projectInfo/projectStructure/projectStructure.style.ts
  src/components/projectInfo/projectStructure/projectStructure.tsx
  src/components/projectInfo/projectSummary/projectSumary.style.ts
  src/components/projectInfo/projectSummary/projectSummary.tsx
  src/components/projectInfo/teamMember/teamMember.style.ts
  src/components/projectInfo/teamMember/teamMember.tsx
  src/components/scenario/buttonGroup/buttonGroup.tsx
  src/components/scenario/dropDown/dropDown.style.ts
  src/components/scenario/dropDown/dropDown.tsx
  src/components/scenario/scenarioModal/scenarioModal.tsx
  src/hooks/sidebar/useGetTeamMember.ts
  src/pages/projectInfo/projectInfo.tsx
  src/pages/scenario/scenario.tsx
  src/types/projectInfo/projectInfo.ts
  src/types/sidebar/sidebar.ts
Labels: ♻️ Refactor

#232 [Feature/#226] 팀원 초대 수락 api 연결
  src/apis/auth/auth.ts
  src/apis/userController/userController.ts
  src/apis/userInfo/userInfo.ts
  src/components/auth/inviteModal/inviteErrorModal.style.ts
  src/components/auth/inviteModal/inviteErrorModal.tsx
  src/components/auth/inviteModal/inviteSuccessModal.tsx
  src/components/auth/inviteModal/inviteTokenExpiredModal.tsx
  src/components/common/modalProvider/modalProvider.tsx
  src/components/findingPassword/findingPasswordStep1.tsx
  src/constants/querykeys/queryKeys.ts
  src/hooks/auth/useInvite.ts
  src/pages/addProject/addProject.style.ts
  src/pages/addProject/addProject.tsx
  src/pages/inviteRedirect/inviteRedirect.tsx
  src/pages/login/login.tsx
  src/pages/loginRedirect/loginRedirect.tsx
  src/pages/signup/signup.tsx
  src/pages/userSetting/userSetting.tsx
  src/routes/index.tsx
  src/types/auth/auth.ts
  src/types/userController/userController.ts
Labels: ✨ Feature

#233 ♻️ [Refactor] sidebar 리팩토링
  src/assets/icons/index.ts
  src/components/common/sidebar/project/project.tsx
  src/components/common/sidebar/project/projectItems.tsx
  src/components/common/sidebar/projectItem/ProjectItem.tsx
  src/components/common/sidebar/projectItems/projectItems.style.ts
  src/components/common/sidebar/projectItems/projectItems.tsx
  src/components/common/sidebar/projectList/projectList.tsx
  src/components/common/sidebar/sidebar.style.ts
  src/components/common/sidebar/sidebar.tsx
  src/constants/projectToggle/projectToggle.ts
  src/types/sidebar/sidebar.ts
Labels: ♻️ Refactor

#237 [Feature] 모달 안내 문구 및 디자인 변경
  src/components/auth/inviteModal/inviteErrorModal.tsx
  src/components/auth/inviteModal/inviteModal.style.ts
  src/components/auth/inviteModal/inviteSuccessModal.tsx
  src/components/auth/inviteModal/inviteTokenExpiredModal.tsx
Labels: ✨ Feature

#240 [Deploy] Deploy
  src/apis/test/test.ts
  src/components/common/searchBar/searchBar.tsx
  src/components/dashboard/searchBar/searchBar.style.ts
  src/components/dashboard/searchBar/searchBar.tsx
  src/components/dashboard/selectBox/selectBox.tsx
  src/components/dashboard/table/dateHeader.tsx
  src/components/dashboard/table/pageNameHeader.tsx
  src/components/dashboard/table/stateHeader.tsx
  src/components/dashboard/table/table.tsx
  src/components/dashboard/table/tableHeader.tsx
  src/constants/state/state.ts
  src/enums/enums.ts
  src/hooks/dashborad/useTableFilter.ts
  src/utils/getSelectName.ts
Labels: 🌏 Deploy

#243 🐞 [BugFix] pageName이 많아졌을 때 표 스크롤 수정
  src/components/dashboard/selectBox/selectBox.style.ts
Labels: 🐞 BugFix

#242 ✨ [Feature] 시나리오 실행 api 연결
  src/apis/scenarioAct/scenarioAct.ts
  src/assets/icons/exit.svg
  src/components/common/modalProvider/modalProvider.tsx
  src/components/scenarioAct/actSection/InnerComponent.tsx
  src/components/scenarioAct/actSection/actSection.tsx
  src/components/scenarioAct/actSection/test.ts
  src/components/scenarioAct/actionItem/actionItem.style.ts
  src/components/scenarioAct/actionItem/actionItem.tsx
  src/components/scenarioAct/addInputForm/addInputForm.style.ts
  src/components/scenarioAct/addInputForm/addInputForm.tsx
  src/components/scenarioAct/characterSelectDropdown/characterSelectDropdown.style.ts
  src/components/scenarioAct/characterSelectDropdown/characterSelectDropdown.tsx
  src/components/scenarioAct/controller/controller.style.ts
  src/components/scenarioAct/controller/controller.tsx
  src/components/scenarioAct/recordItem/recordItem.tsx
  src/components/scenarioAct/scenarioActModal/scenarioActModal.style.ts
  src/components/scenarioAct/scenarioActModal/scenarioActModal.tsx
  src/components/scenarioAct/scenarioItem/scenarioItem.style.ts
  src/components/scenarioAct/scenarioItem/scenarioItem.tsx
  src/components/scenarioAct/selectDropdown/selectDropdown.tsx
  src/components/scenarioAct/thinDropdown/thinDropdown.tsx
  src/enums/enums.ts
  src/hooks/scenarioAct/useAction.ts
  src/hooks/scenarioAct/useExecuteScenario.ts
  src/hooks/scenarioAct/useFetchPageSource.ts
  src/hooks/scenarioAct/useProjectInfo.ts
  src/hooks/scenarioAct/useScenario.ts
  src/hooks/scenarioAct/useScenarioList.ts
  src/hooks/scenarioAct/useWebsocket.ts
  src/pages/scenarioAct/scenarioAct.tsx
  src/slices/scenarioActSlice.ts
  src/types/scenarioAct/scenarioAct.ts
  src/utils/getCssSelector.ts
  src/utils/getXPath.ts
Labels: ✨ Feature

#248 🐞 [BugFix/#246] 시나리오 실행 역할 선택 오류 해결
  src/components/scenarioAct/actSection/actSection.tsx
  src/components/scenarioAct/controller/controller.tsx
  src/pages/scenarioAct/scenarioAct.style.ts
  src/pages/scenarioAct/scenarioAct.tsx
Labels: 🐞 BugFix

#252 [Refactor] 시나리오 클릭시 활성화 되게 수정
  src/components/scenario/characterHeader/characterHeader.tsx
  src/components/scenario/characterList/characterList.tsx
  src/components/scenario/scenarioItem/scenarioItem.style.ts
  src/components/scenario/scenarioItem/scenarioItem.tsx
  src/pages/scenario/scenario.tsx
Labels: ♻️ Refactor

#249 ♻️ [Refactor] 표 select로 변경시 통계 리렌더링 이슈 해결
  src/components/dashboard/projectStatistics/projectStatistics.tsx
  src/components/dashboard/table/pageNameHeader.tsx
  src/components/dashboard/table/table.style.ts
  src/components/dashboard/table/table.tsx
  src/hooks/common/customQuery.ts
  src/hooks/common/useProjectId.ts
  src/hooks/test/usePaginateTestList.ts
  src/pages/dashboard/dashboard.tsx
Labels: ♻️ Refactor

#256 🌎 [Deploy] 웹소켓 env 적용 후 배포
  .github/workflows/main.yaml
  src/components/dashboard/projectStatistics/projectStatistics.tsx
  src/components/dashboard/table/pageNameHeader.tsx
  src/components/dashboard/table/table.style.ts
  src/components/dashboard/table/table.tsx
  src/components/scenario/characterHeader/characterHeader.tsx
  src/components/scenario/characterList/characterList.tsx
  src/components/scenario/scenarioItem/scenarioItem.style.ts
  src/components/scenario/scenarioItem/scenarioItem.tsx
  src/hooks/common/customQuery.ts
  src/hooks/common/useProjectId.ts
  src/hooks/test/usePaginateTestList.ts
  src/pages/dashboard/dashboard.tsx
  src/pages/scenario/scenario.tsx
Labels: 🌏 Deploy

#258 [Bug] 페이지 버튼 반환 함수 수정
  src/utils/getPageNumbers.ts
Labels: 🐞 BugFix

#261 🐞 [BugFix] 표 페이지네이션 버튼 오류 수정 및 표 캘린더 오류 수정
  src/components/dashboard/calendar/calendar.tsx
  src/components/dashboard/selectBox/selectBox.style.ts
  src/components/dashboard/table/dateHeader.tsx
  src/components/dashboard/table/table.style.ts
  src/components/dashboard/table/table.tsx
  src/slices/calendarSlice.ts
  src/utils/formatDate.ts
  src/utils/getPageNumbers.ts
Labels: 🐞 BugFix

#262 🌏 [Deploy] 표 관련 오류사항 수정 배포
  src/components/dashboard/calendar/calendar.tsx
  src/components/dashboard/selectBox/selectBox.style.ts
  src/components/dashboard/table/dateHeader.tsx
  src/components/dashboard/table/table.style.ts
  src/components/dashboard/table/table.tsx
  src/slices/calendarSlice.ts
  src/utils/formatDate.ts
  src/utils/getPageNumbers.ts
Labels: 🌏 Deploy

#265 [Feature/#247] 시나리오 실행 남은 기능들
  src/apis/scenarioAct/scenarioAct.ts
  src/components/scenarioAct/actSection/InnerComponent.tsx
  src/components/scenarioAct/actionItem/actionItem.tsx
  src/components/scenarioAct/addInputForm/addInputForm.tsx
  src/components/scenarioAct/input/input.style.ts
  src/components/scenarioAct/input/input.tsx
  src/components/scenarioAct/scenarioItem/scenarioItem.tsx
  src/hooks/scenarioAct/useWebsocket.ts
  src/pages/scenarioAct/scenarioAct.tsx
  src/slices/scenarioActSlice.ts
Labels: ✨ Feature

#266 🌏 [Deploy] 시나리오 실행 projectUrl 연결 수정 배포
  src/apis/scenarioAct/scenarioAct.ts
  src/components/scenarioAct/actSection/InnerComponent.tsx
  src/components/scenarioAct/actionItem/actionItem.tsx
  src/components/scenarioAct/addInputForm/addInputForm.tsx
  src/components/scenarioAct/input/input.style.ts
  src/components/scenarioAct/input/input.tsx
  src/components/scenarioAct/scenarioItem/scenarioItem.tsx
  src/hooks/scenarioAct/useWebsocket.ts
  src/pages/scenarioAct/scenarioAct.tsx
  src/slices/scenarioActSlice.ts
Labels: 🌏 Deploy

#269 ✨ [Feature] not-found page 버튼 추가
  src/assets/icons/back.svg
  src/assets/icons/index.ts
  src/pages/error/error.style.ts
  src/pages/error/error.tsx
Labels: ✨ Feature

#267 [Bugfix/#263] 프로젝트 헤더 (프로젝트 네임, 프로젝트 스택) 공용컴포넌트 분리, 레이아웃에 추가
  src/apis/projectInfo/projectInfo.ts
  src/components/common/modal/modal.style.ts
  src/components/common/modalProvider/modalProvider.tsx
  src/components/common/projectHeader/projectHeader.style.ts
  src/components/common/projectHeader/projectHeader.tsx
  src/components/common/projectTitle/projectTitle.style.ts
  src/components/common/projectTitle/projectTitle.tsx
  src/components/common/sidebar/projectProfile/projectProfile.tsx
  src/components/dashboard/projectStatistics/projectStatistics.style.ts
  src/components/dashboard/projectStatistics/projectStatistics.tsx
  src/components/projectInfo/deleteProjectModal/deleteProjectModal.style.ts
  src/components/projectInfo/deleteProjectModal/deleteProjectModal.tsx
  src/components/projectInfo/editProjectModal/editProjectModal.style.ts
  src/components/projectInfo/editProjectModal/editProjectModal.tsx
  src/enums/enums.ts
  src/hooks/projectInfo/useProjectInfo.ts
  src/layouts/main/mainLayout.style.ts
  src/layouts/main/mainLayout.tsx
  src/pages/dashboard/dashboard.style.ts
  src/pages/scenario/scenario.style.ts
  src/pages/scenario/scenario.tsx
  src/types/projectInfo/projectInfo.ts
Labels: 🐞 BugFix

#274 [Feature] 프로젝트 삭제 모달에 취소 버튼 추가
  src/components/projectInfo/deleteProjectModal/deleteProjectModal.tsx
Labels: ✨ Feature

#271 [Refactor] 프로젝트 기본 이미지를 프로필 컴포넌트에 추가
  src/assets/icons/DefaultProject.svg
  src/components/common/profile/profile.tsx
  src/components/common/projectTitle/projectTitle.tsx
  src/components/common/sidebar/project/project.tsx
  src/components/mypage/project/project.tsx
  src/pages/userInfo/userInfo.style.ts
Labels: ♻️ Refactor

#276 [Refactor/#275] 모달 로딩 디자인 변경 및 반영
  src/components/common/loading/modalLoading.style.ts
  src/components/common/loading/modalLoading.tsx
  src/components/common/projectTitle/projectTitle.tsx
  src/components/common/sidebar/projectModal/projectModal.tsx
  src/components/projectInfo/editProjectModal/editProjectModal.tsx
  src/components/projectInfo/inviteModal/inviteModal.tsx
  src/components/scenario/scenarioModal/scenarioModal.tsx
  src/components/scenario/scenarioModal/scenarioModal/scenarioModalStep1.tsx
Labels: ♻️ Refactor

#281 [Bugfix] 이미지 url이 올바르지 않을 때 깨져보이는 현상 예외처리
  src/components/common/profile/profile.tsx
Labels: 🐞 BugFix

#282 [Refactor] 프로젝트 리더만 edit, delete 버튼이 보이도록 수정
  src/components/common/projectHeader/projectHeader.tsx
  src/types/projectInfo/projectInfo.ts
Labels: ♻️ Refactor

#278 [Refactor/#253] 마이페이지 리팩토링
  src/components/mypage/myProfile/MyProfile.style.ts
  src/components/mypage/projectList/projectList.style.ts
  src/components/mypage/projectList/projectList.tsx
  src/components/userInfo/otherUserProjectList/otherUserProjectList.tsx
  src/components/userInfo/userProfile/userProfile.style.ts
  src/components/userInfo/userProfile/userProfile.tsx
  src/hooks/userInfo/useOtherUserInfo.ts
  src/pages/mypage/mypage.tsx
  src/pages/userInfo/userInfo.style.ts
  src/pages/userInfo/userInfo.tsx
Labels: ♻️ Refactor

#279 [Refactor] auth 리팩토링
  src/apis/axiosInstance.ts
  src/components/common/sidebar/logtoutModal/logoutModal.tsx
  src/hooks/auth/useUserAuth.ts
  src/pages/login/login.tsx
  src/pages/signup/signup.tsx
Labels: ♻️ Refactor

#244 [Refactor/#234] information 페이지 기능 오류 수정
  src/components/common/sidebar/projectModal/projectModal.tsx
  src/components/projectInfo/characterBox/characterBox.style.ts
  src/components/projectInfo/characterBox/characterBox.tsx
  src/components/projectInfo/inviteModal/inviteModal.tsx
  src/components/projectInfo/projectInput/projectInput.style.ts
  src/components/projectInfo/projectInput/projectInput.tsx
  src/components/projectInfo/projectIntroduction/projectIntro.style.ts
  src/components/projectInfo/projectIntroduction/projectIntro.tsx
  src/components/projectInfo/projectStructure/projectStructure.style.ts
  src/components/projectInfo/projectSummary/projectSumary.style.ts
  src/components/projectInfo/teamMember/teamMember.style.ts
  src/pages/projectInfo/projectInfo.style.ts
  src/pages/projectInfo/projectInfo.tsx
Labels: 🐞 BugFix, ✨ Feature

#286 ✨ [Feature] 대시보드 레이아웃 수정
  src/components/common/loading/loading.style.ts
  src/components/dashboard/selectBox/selectBox.style.ts
  src/pages/dashboard/dashboard.style.ts
Labels: ✨ Feature

#291 ♻️ [Refactor] 대시보드에서 사용하지 않는 api 요청 방지
  src/components/common/projectHeader/projectHeader.tsx
  src/components/dashboard/table/pageNameHeader.tsx
  src/components/projectInfo/editProjectModal/editProjectModal.tsx
  src/components/projectInfo/projectSummary/projectSummary.tsx
  src/hooks/projectInfo/useEditProject.ts
  src/hooks/projectInfo/useGetPageSummary.ts
  src/hooks/projectInfo/useProjectExtractInfo.ts
  src/hooks/projectInfo/useProjectInfo.ts
  src/pages/addProject/addProject.tsx
Labels: ♻️ Refactor

#298 ✨ [Feature] 에러 모달 수정
  src/components/common/modal/modal.style.ts
  src/components/dashboard/errorModal/errorModal.style.ts
  src/components/dashboard/table/table.style.ts
  src/components/scenarioAct/scenarioActModal/scenarioActModal.style.ts
Labels: ✨ Feature

#299 🌏 [Deploy] 에러 모달 수정 배포 브랜치에 반영
  src/components/common/modal/modal.style.ts
  src/components/dashboard/errorModal/errorModal.style.ts
  src/components/dashboard/table/table.style.ts
  src/components/scenarioAct/scenarioActModal/scenarioActModal.style.ts
Labels: 🌏 Deploy

#301 [Refactor/#300] axiosInterceptor 리팩토링
  src/apis/axiosInstance.ts
Labels: ♻️ Refactor

#302 [Deploy] 배포
  src/apis/axiosInstance.ts
Labels: 🌏 Deploy

#305 ✨ [Feature] 대시보드 100% 짤리는 이슈 수정
  src/components/dashboard/progressBar/progressBar.style.ts
Labels: ✨ Feature

#306 🌏 [Deploy] 대시보드 100% 짤리는 부분 수정
  src/components/dashboard/progressBar/progressBar.style.ts
Labels: ✨ Feature

#310 [Feature/#285] qa 피드백 반영
  src/apis/projectInfo/projectInfo.ts
  src/assets/icons/arrow_right.svg
  src/assets/icons/menu_dark.svg
  src/components/common/modalProvider/modalProvider.tsx
  src/components/projectInfo/ChangeOwnerModal/changeOwnerModal.style.ts
  src/components/projectInfo/ChangeOwnerModal/changeOwnerModal.tsx
  src/components/projectInfo/characterBox/characterBox.style.ts
  src/components/projectInfo/deleteTeamMember/deleteTeamMemberModal.style.ts
  src/components/projectInfo/deleteTeamMember/deleteTeamMemberModal.tsx
  src/components/projectInfo/menu/menu.style.ts
  src/components/projectInfo/menu/menu.tsx
  src/components/projectInfo/projectInput/projectInput.style.ts
  src/components/projectInfo/projectInput/projectInput.tsx
  src/components/projectInfo/projectStructure/projectStructure.style.ts
  src/components/projectInfo/projectSummary/projectSumary.style.ts
  src/components/projectInfo/teamMember/teamMember.style.ts
  src/components/projectInfo/teamMember/teamMember.tsx
  src/components/projectInfo/toolTip/toolTip.style.ts
  src/hooks/projectInfo/useChangeOwner.ts
  src/pages/addProject/addProject.style.ts
  src/pages/addProject/addProject.tsx
  src/pages/projectInfo/projectInfo.style.ts
  src/pages/projectInfo/projectInfo.tsx
  src/types/projectInfo/projectInfo.ts
Labels: ✨ Feature, ♻️ Refactor

#312 [bugfix] api 요청 시 projectId가 0으로 가는 에러 해결
  src/components/projectInfo/ChangeOwnerModal/changeOwnerModal.tsx
  src/components/projectInfo/menu/menu.tsx
  src/components/projectInfo/teamMember/teamMember.tsx
Labels: 🐞 BugFix

#313 [Deploy] 배포
  src/apis/projectInfo/projectInfo.ts
  src/assets/icons/arrow_right.svg
  src/assets/icons/menu_dark.svg
  src/components/common/modalProvider/modalProvider.tsx
  src/components/projectInfo/ChangeOwnerModal/changeOwnerModal.style.ts
  src/components/projectInfo/ChangeOwnerModal/changeOwnerModal.tsx
  src/components/projectInfo/characterBox/characterBox.style.ts
  src/components/projectInfo/deleteTeamMember/deleteTeamMemberModal.style.ts
  src/components/projectInfo/deleteTeamMember/deleteTeamMemberModal.tsx
  src/components/projectInfo/menu/menu.style.ts
  src/components/projectInfo/menu/menu.tsx
  src/components/projectInfo/projectInput/projectInput.style.ts
  src/components/projectInfo/projectInput/projectInput.tsx
  src/components/projectInfo/projectStructure/projectStructure.style.ts
  src/components/projectInfo/projectSummary/projectSumary.style.ts
  src/components/projectInfo/teamMember/teamMember.style.ts
  src/components/projectInfo/teamMember/teamMember.tsx
  src/components/projectInfo/toolTip/toolTip.style.ts
  src/hooks/projectInfo/useChangeOwner.ts
  src/pages/addProject/addProject.style.ts
  src/pages/addProject/addProject.tsx
  src/pages/projectInfo/projectInfo.style.ts
  src/pages/projectInfo/projectInfo.tsx
  src/types/projectInfo/projectInfo.ts
Labels: 🌏 Deploy

#315 [bugfix] svg 파일이 잘못됨
  src/assets/icons/arrow_right.svg
  src/assets/icons/moreInfo.svg
  src/components/projectInfo/teamMember/teamMember.tsx
Labels: 🐞 BugFix

#317 [Feature/#307] 캐릭터 생성 시 ai 시나리오를 선택해서 만들 수 있도록 수정
  src/apis/scenario/scenario.ts
  src/components/scenario/scenarioModal/scenarioModal.tsx
  src/components/scenario/scenarioModal/scenarioModal/scenarioModalStep.style.ts
  src/components/scenario/scenarioModal/scenarioModal/scenarioModalStep1.tsx
  src/components/scenario/scenarioModal/scenarioModal/scenarioModalStep2.tsx
  src/types/scenario/scenario.ts
Labels: ✨ Feature

#318 [Deploy] 배포
  src/apis/scenario/scenario.ts
  src/assets/icons/arrow_right.svg
  src/assets/icons/moreInfo.svg
  src/components/projectInfo/teamMember/teamMember.tsx
  src/components/scenario/scenarioModal/scenarioModal.tsx
  src/components/scenario/scenarioModal/scenarioModal/scenarioModalStep.style.ts
  src/components/scenario/scenarioModal/scenarioModal/scenarioModalStep1.tsx
  src/components/scenario/scenarioModal/scenarioModal/scenarioModalStep2.tsx
  src/types/scenario/scenario.ts
Labels: 🌏 Deploy

#320 [Refactor] 마이페이지 스타일 수정
  src/components/common/sidebar/logtoutModal/logoutModal.tsx
  src/pages/mypage/mypage.style.ts
Labels: ♻️ Refactor

#323 [Refactor] 맡은 부분 리팩토링
  src/components/userInfo/otherUserProjectList/otherUserProjectList.tsx
  src/hooks/userInfo/useOtherUserInfo.ts
  src/hooks/userInfo/useOtherUserProjects.ts
  src/pages/findingPassword/findingPassword.tsx
  src/pages/userInfo/userInfo.tsx
Labels: ♻️ Refactor

#309 [Refactor/#296] 시나리오 실행 이슈 해결
  src/apis/scenarioAct/scenarioAct.ts
  src/assets/icons/wait.svg
  src/components/scenarioAct/actSection/InnerComponent.tsx
  src/components/scenarioAct/actSection/actSection.style.ts
  src/components/scenarioAct/actSection/test.ts
  src/components/scenarioAct/actionItem/actionItem.style.ts
  src/components/scenarioAct/actionItem/actionItem.tsx
  src/components/scenarioAct/addInputForm/addInputForm.style.ts
  src/components/scenarioAct/addInputForm/addInputForm.tsx
  src/components/scenarioAct/characterSelectDropdown/characterSelectDropdown.style.ts
  src/components/scenarioAct/characterSelectDropdown/characterSelectDropdown.tsx
  src/components/scenarioAct/continueModal/continueModal.style.ts
  src/components/scenarioAct/controller/controller.style.ts
  src/components/scenarioAct/controller/controller.tsx
  src/components/scenarioAct/input/input.style.ts
  src/components/scenarioAct/input/input.tsx
  src/components/scenarioAct/modifyInputForm/modifyInputForm.style.ts
  src/components/scenarioAct/modifyInputForm/modifyInputForm.tsx
  src/components/scenarioAct/recordItem/recordItem.style.ts
  src/components/scenarioAct/recordItem/recordItem.tsx
  src/components/scenarioAct/scenarioItem/scenarioItem.style.ts
  src/components/scenarioAct/scenarioItem/scenarioItem.tsx
  src/components/scenarioAct/thinDropdown/thinDropdown.style.ts
  src/components/scenarioAct/thinDropdown/thinDropdown.tsx
  src/enums/enums.ts
  src/hooks/scenarioAct/useScenarioList.ts
  src/pages/scenarioAct/scenarioAct.tsx
  src/slices/scenarioActSlice.ts
  src/utils/getCssSelector.ts
  src/utils/getXPath.ts
Labels: ♻️ Refactor

#324 [Deploy] 배포
  src/apis/scenarioAct/scenarioAct.ts
  src/assets/icons/wait.svg
  src/components/scenarioAct/actSection/InnerComponent.tsx
  src/components/scenarioAct/actSection/actSection.style.ts
  src/components/scenarioAct/actSection/test.ts
  src/components/scenarioAct/actionItem/actionItem.style.ts
  src/components/scenarioAct/actionItem/actionItem.tsx
  src/components/scenarioAct/addInputForm/addInputForm.style.ts
  src/components/scenarioAct/addInputForm/addInputForm.tsx
  src/components/scenarioAct/characterSelectDropdown/characterSelectDropdown.style.ts
  src/components/scenarioAct/characterSelectDropdown/characterSelectDropdown.tsx
  src/components/scenarioAct/continueModal/continueModal.style.ts
  src/components/scenarioAct/controller/controller.style.ts
  src/components/scenarioAct/controller/controller.tsx
  src/components/scenarioAct/input/input.style.ts
  src/components/scenarioAct/input/input.tsx
  src/components/scenarioAct/modifyInputForm/modifyInputForm.style.ts
  src/components/scenarioAct/modifyInputForm/modifyInputForm.tsx
  src/components/scenarioAct/recordItem/recordItem.style.ts
  src/components/scenarioAct/recordItem/recordItem.tsx
  src/components/scenarioAct/scenarioItem/scenarioItem.style.ts
  src/components/scenarioAct/scenarioItem/scenarioItem.tsx
  src/components/scenarioAct/thinDropdown/thinDropdown.style.ts
  src/components/scenarioAct/thinDropdown/thinDropdown.tsx
  src/components/userInfo/otherUserProjectList/otherUserProjectList.tsx
  src/enums/enums.ts
  src/hooks/scenarioAct/useScenarioList.ts
  src/hooks/userInfo/useOtherUserInfo.ts
  src/hooks/userInfo/useOtherUserProjects.ts
  src/pages/findingPassword/findingPassword.tsx
  src/pages/scenarioAct/scenarioAct.tsx
  src/pages/userInfo/userInfo.tsx
  src/slices/scenarioActSlice.ts
  src/utils/getCssSelector.ts
  src/utils/getXPath.ts
Labels: 🌏 Deploy

#328 [Refactor/#325] 시나리오 실행 UI 수정
  src/components/scenarioAct/addInputForm/addInputForm.tsx
  src/components/scenarioAct/continueModal/continueModal.style.ts
  src/components/scenarioAct/controller/controller.style.ts
  src/components/scenarioAct/modifyInputForm/modifyInputForm.tsx
Labels: ♻️ Refactor

#329 [Deploy] 배포
  src/components/common/projectHeader/projectHeader.tsx
  src/components/common/sidebar/projectModal/projectModal.tsx
  src/components/projectInfo/inviteModal/inviteModal.tsx
  src/components/projectInfo/pageModal/pageModal.tsx
  src/components/scenarioAct/addInputForm/addInputForm.tsx
  src/components/scenarioAct/continueModal/continueModal.style.ts
  src/components/scenarioAct/controller/controller.style.ts
  src/components/scenarioAct/modifyInputForm/modifyInputForm.tsx
Labels: 🌏 Deploy

#331 [Refactor/#330] invalidate 쿼리 추가
  src/pages/addProject/addProject.tsx
Labels: 🐞 BugFix

#334 [Deploy] 배포
  src/components/scenario/scenarioModal/scenarioModal/scenarioModalStep1.tsx
  src/pages/addProject/addProject.tsx
Labels: 🌏 Deploy

#336 [Refactor] 로그아웃 시 캐시 지우기 및 효율성 증가 시키기
  src/components/common/sidebar/logtoutModal/logoutModal.tsx
  src/components/projectInfo/ChangeOwnerModal/changeOwnerModal.tsx
  src/components/projectInfo/deleteProjectModal/deleteProjectModal.tsx
  src/components/projectInfo/deleteTeamMember/deleteTeamMemberModal.tsx
  src/pages/login/login.tsx
  src/pages/signup/signup.tsx
Labels: ♻️ Refactor

#337 [Deploy] 배포
  src/components/common/sidebar/logtoutModal/logoutModal.tsx
  src/components/projectInfo/ChangeOwnerModal/changeOwnerModal.tsx
  src/components/projectInfo/deleteProjectModal/deleteProjectModal.tsx
  src/components/projectInfo/deleteTeamMember/deleteTeamMemberModal.tsx
  src/pages/login/login.tsx
  src/pages/signup/signup.tsx
Labels: 🌏 Deploy
