Repository QASTUDIODEV/WEB_QASTUDIO, pull requests merged in 2025-01, with the labels that each got.

#2 [Feature/#1] font, color 및 폴더 구조 세팅
  commitlint.config.cjs
  eslint/import.mjs
  index.html
  package.json
  pnpm-lock.yaml
  public/fonts/PretendardVariable.woff2
  src/App.tsx
  src/apis/axiosInstance.ts
  src/apis/queryClient.ts
  src/components/common/input/input.style.ts
  src/components/common/input/input.tsx
  src/hooks/common/customQuery.ts
  src/layouts/auth/auth.style.ts
  src/layouts/auth/auth.tsx
  src/main.tsx
  src/pages/login/login.style.ts
  src/pages/login/login.tsx
  src/routes/index.tsx
  src/styles/global.ts
  src/styles/index.css
  src/styles/styled.d.ts
  src/styles/theme.ts
  src/types/common/common.ts
  tsconfig.app.json
  vite.config.ts
Labels: ⚙️ Setting

#5 [Feature/#4] Redux 설치 및 세팅
  package.json
  pnpm-lock.yaml
  src/hooks/common/useCustomRedux.ts
  src/main.tsx
  src/slices/modalSlice.ts
  src/store/store.ts
Labels: ⚙️ Setting

#6 [Feature/#3] route 설정, 기본적인 폴더 및 파일 세팅
  src/components/common/sidebar/sidebar.style.ts
  src/components/common/sidebar/sidebar.tsx
  src/layouts/main/mainLayout.style.ts
  src/layouts/main/mainLayout.tsx
  src/pages/auth/basicOAuth.tsx
  src/pages/auth/githubOAuth.tsx
  src/pages/auth/googleOAuth.tsx
  src/pages/auth/kakaoOAuth.tsx
  src/pages/dashboard/dashboard.style.ts
  src/pages/dashboard/dashboard.tsx
  src/pages/mypage/mypage.style.ts
  src/pages/mypage/mypage.tsx
  src/pages/projectInfo/projectInfo.style.ts
  src/pages/projectInfo/projectInfo.tsx
  src/pages/scenario/scenario.style.ts
  src/pages/scenario/scenario.tsx
  src/pages/scenarioAct/scenarioAct.style.ts
  src/pages/scenarioAct/scenarioAct.tsx
  src/pages/signup/signup.style.ts
  src/pages/signup/signup.tsx
  src/routes/index.tsx
Labels: ⚙️ Setting

#14 [Feature/#13] 아이콘 추가 및 사이트 로고 반영
  index.html
  package.json
  pnpm-lock.yaml
  public/icons/logo.svg
  public/vite.svg
  src/assets/icons/Line_arrow_down.svg
  src/assets/icons/Line_arrow_up.svg
  src/assets/icons/add.svg
  src/assets/icons/arrow_down.svg
  src/assets/icons/arrow_left.svg
  src/assets/icons/arrow_right.svg
  src/assets/icons/arrow_up.svg
  src/assets/icons/calender.svg
  src/assets/icons/check box_false.svg
  src/assets/icons/check box_true.svg
  src/assets/icons/check_circle.svg
  src/assets/icons/click.svg
  src/assets/icons/del.svg
  src/assets/icons/del_circle.svg
  src/assets/icons/delete.svg
  src/assets/icons/done.svg
  src/assets/icons/edit.svg
  src/assets/icons/eyes.svg
  src/assets/icons/fail_circle.svg
  src/assets/icons/file.svg
  src/assets/icons/file_branch.svg
  src/assets/icons/globe.svg
  src/assets/icons/grid.svg
  src/assets/icons/info.svg
  src/assets/icons/location_arrow.svg
  src/assets/icons/logo.svg
  src/assets/icons/mobile.svg
  src/assets/icons/nextjs.svg
  src/assets/icons/package.svg
  src/assets/icons/pause.svg
  src/assets/icons/play.svg
  src/assets/icons/search.svg
  src/assets/icons/star.svg
  src/assets/icons/upload.svg
  src/assets/icons/user.svg
  src/assets/icons/user_circle.svg
  src/assets/icons/user_profile.svg
  src/assets/icons/web.svg
  src/assets/react.svg
  src/vite-env.d.ts
  tsconfig.app.json
  vite.config.ts
Labels: ✨ Feature

#16 [Feature/#15] profile 컴포넌트 props 변경
  src/components/common/profile/profile.tsx
Labels: ✨ Feature

#19 feat: 인풋 공용 컴포넌트 제작
  src/components/common/input/input.style.ts
  src/components/common/input/input.tsx
Labels: ✨ Feature

#23 [Feature/#22] 버튼 공용 컴포넌트 제작
  src/components/common/button/button.style.ts
  src/components/common/button/button.tsx
Labels: ✨ Feature

#25 [Feature/#24] 프로젝트 첫 페이지 UI 구현
  src/pages/addProject/addProject.style.ts
  src/pages/addProject/addProject.tsx
  src/routes/index.tsx
Labels: ✨ Feature

#27 [Feature/#26] 마이페이지 라우트 수정
  src/routes/index.tsx
Labels: ✨ Feature

#29 [Feature/#28] 누락된 파일 추가
  src/assets/icons/defaultProfile.svg
Labels: 🐞 BugFix

#32 [Feature/#10] modal 컴포넌트 구현
  index.html
  package.json
  src/components/common/modal/modal.style.ts
  src/components/common/modal/modal.tsx
  src/hooks/common/usePortal.ts
  src/pages/dashboard/dashboard.style.ts
  src/pages/dashboard/dashboard.tsx
  src/slices/modalSlice.ts
  src/styles/media.ts
  src/styles/theme.ts
Labels: ✨ Feature

#34 [Feature/#22] 버튼 공용컴포넌트 색상 옵션 추가
  src/components/common/button/button.style.ts
  src/components/common/button/button.tsx
Labels: ✨ Feature

#38 [Feature/#37] 소셜로고 컴포넌트 수정, 컴포넌트 수정에 따른 사용법 반영
  src/components/auth/module/module.style.ts
  src/components/auth/socialLogo/socialLogo.style.ts
  src/components/auth/socialLogo/socialLogo.tsx
  src/pages/login/login.tsx
  src/pages/signup/signup.style.ts
  src/pages/signup/signup.tsx
Labels: ✨ Feature

#41 [Feature/#40] 브라우저 warning 제거를 위한 props 타입 및 용어 변경
  src/components/auth/socialLogo/socialLogo.style.ts
  src/components/auth/socialLogo/socialLogo.tsx
Labels: ✨ Feature

#39 [Feature/#11] Sidebar 공용 컴포넌트 UI 업데이트
  src/assets/icons/logout.svg
  src/components/common/sidebar/ProjectItem.tsx
  src/components/common/sidebar/sidebar.style.ts
  src/components/common/sidebar/sidebar.tsx
  src/layouts/main/mainLayout.style.ts
Labels: ✨ Feature

#44 [Feature/#43] OutletWrapper 생성
  src/layouts/main/mainLayout.style.ts
  src/layouts/main/mainLayout.tsx
Labels: ✨ Feature

#46 [Feature/#45] 레이아웃이 깨지는 현상 수정
  src/layouts/main/mainLayout.style.ts
Labels: 🐞 BugFix

#50 ✨ [Feature] modal 컴포넌트 수정
  src/components/common/modal/modal.style.ts
  src/components/common/modal/modal.tsx
Labels: ✨ Feature

#48 [Feature/#47] 프로젝트 타이틀 - 공용 컴포넌트 구현
  src/assets/icons/js.svg
  src/assets/icons/react.svg
  src/components/common/projectTitle/projectTitle.style.ts
  src/components/common/projectTitle/projectTitle.tsx
  src/enums/enums.ts
  src/utils/getIcon.ts
Labels: ✨ Feature

#42 [Feature/#35] 로그인, 회원가입, 비밀번호 찾기 react hook form으로 리팩토링
  package.json
  pnpm-lock.yaml
  src/apis/auth/auth.ts
  src/apis/images/images.ts
  src/components/auth/authButton/authButton.style.ts
  src/components/auth/authButton/authButton.tsx
  src/components/auth/authInput/authInput.tsx
  src/components/auth/codeInput/codeInput.tsx
  src/components/auth/module/module.style.ts
  src/components/auth/module/module.tsx
  src/components/auth/socialLogo/socialLogo.style.ts
  src/components/auth/socialLogo/socialLogo.tsx
  src/constants/querykeys/queryKeys.ts
  src/hooks/auth/useForm.ts
  src/hooks/auth/useGetOAuth.ts
  src/hooks/common/useCustomMutation.ts
  src/hooks/common/useGetPresignedURL.ts
  src/hooks/common/useUploadPresignedURL.ts
  src/pages/auth/kakaoOAuth.tsx
  src/pages/findingPassword/findingPassword.tsx
  src/pages/login/login.style.ts
  src/pages/login/login.tsx
  src/pages/signup/signup.style.ts
  src/pages/signup/signup.tsx
  src/pages/userSetting/userSetting.style.ts
  src/pages/userSetting/userSetting.tsx
  src/routes/index.tsx
  src/types/auth/auth.ts
  src/utils/validate.ts
Labels: ♻️ Refactor

#55 [Feature/#53] 인풋 공용 컴포넌트 box-sizing 변경
  src/components/auth/module/module.tsx
  src/components/common/input/input.style.ts
  src/components/common/input/input.tsx
  src/components/common/input/validationMessage.style.ts
  src/components/common/input/validationMessage.tsx
  src/pages/scenario/scenario.tsx
Labels: ✨ Feature

#57 ✨ [Feature] 대시보드 UI 구현
  package.json
  pnpm-lock.yaml
  src/assets/icons/arrow_right_green.svg
  src/assets/icons/arrow_right_red.svg
  src/assets/icons/fail.svg
  src/assets/icons/success.svg
  src/components/common/modal/modal.style.ts
  src/components/common/modal/modal.tsx
  src/components/common/searchBar/searchBar.style.ts
  src/components/common/searchBar/searchBar.tsx
  src/components/common/sidebar/sidebar.style.ts
  src/components/dashboard/errorModal/errorModal.style.ts
  src/components/dashboard/errorModal/errorModal.tsx
  src/components/dashboard/percentLabel/percentLabel.style.ts
  src/components/dashboard/percentLabel/percentLabel.tsx
  src/components/dashboard/progressBar/progressBar.style.ts
  src/components/dashboard/progressBar/progressBar.tsx
  src/components/dashboard/projectInfoBox/projectInfoBox.style.ts
  src/components/dashboard/projectInfoBox/projectInfoBox.tsx
  src/components/dashboard/table/table.style.ts
  src/components/dashboard/table/table.tsx
  src/hooks/common/usePortal.ts
  src/mocks/tableData.ts
  src/pages/dashboard/dashboard.style.ts
  src/pages/dashboard/dashboard.tsx
  src/slices/modalSlice.ts
  src/store/store.ts
  src/styles/global.ts
  src/styles/media.ts
Labels: ✨ Feature

#63 ⚙️ [Setting] ci/cd setting
  .github/workflows/ci.yaml
  .github/workflows/main.yaml
Labels: ✨ Feature

#62 [Feature/#61] 공용컴포넌트 변경에 따른 수정, 라우트 추가
  src/pages/findingPassword/findingPassword.tsx
  src/pages/signup/signup.tsx
  src/pages/userSetting/userSetting.style.ts
  src/pages/userSetting/userSetting.tsx
  src/routes/index.tsx
Labels: ✨ Feature

#59 [Feature/#21] Mypage UI 구현
  src/apis/axiosInstance.ts
  src/apis/images/images.ts
  src/apis/mypage/mypage.ts
  src/apis/userController/userController.ts
  src/assets/icons/arrow_left.svg
  src/assets/icons/arrow_right.svg
  src/components/auth/module/module.tsx
  src/components/mypage/myProfile/MyProfile.style.ts
  src/components/mypage/myProfile/myProfile.tsx
  src/components/mypage/project/project.style.ts
  src/components/mypage/project/project.tsx
  src/components/mypage/projectList/projectList.style.ts
  src/components/mypage/projectList/projectList.tsx
  src/components/mypage/projectNum/projectNum.style.ts
  src/components/mypage/projectNum/projectNum.tsx
  src/constants/querykeys/queryKeys.ts
  src/hooks/common/useGetPresignedURL.ts
  src/hooks/images/useGetPresignedURL.ts
  src/hooks/images/useUploadPresignedURL.ts
  src/hooks/userController/userController.ts
  src/pages/mypage/mypage.style.ts
  src/pages/mypage/mypage.tsx
  src/pages/userSetting/userSetting.tsx
  src/types/mypage/mypage.ts
  src/types/userController/userController.ts
  src/utils/findUnlinkedSocials.ts
  src/utils/validate.ts
Labels: ✨ Feature

#70 [Feature/#69] 프로필 공용 컴포넌트 css 추가
  src/components/common/profile/profile.style.ts
Labels: ✨ Feature

#71 ✨ [Feature] 대시보드 레이아웃 수정
  src/assets/icons/arrow_left.svg
  src/assets/icons/arrow_right.svg
  src/components/dashboard/progressBar/progressBar.style.ts
  src/components/dashboard/progressBar/progressBar.tsx
  src/components/dashboard/table/table.style.ts
  src/components/dashboard/table/table.tsx
  src/hooks/common/useDebounce.ts
  src/pages/dashboard/dashboard.style.ts
  src/pages/dashboard/dashboard.tsx
Labels: ✨ Feature

#74 [Feature/#11] sidebar UI 구현
  src/assets/icons/camera.svg
  src/components/common/sidebar/logtoutModal/logoutModal.style.ts
  src/components/common/sidebar/logtoutModal/logoutModal.tsx
  src/components/common/sidebar/projectModal/projectModal.style.ts
  src/components/common/sidebar/projectModal/projectModal.tsx
  src/components/common/sidebar/sidebar.style.ts
  src/components/common/sidebar/sidebar.tsx
Labels: ✨ Feature

#64 [Feature/#20] 시나리오 UI 구현
  src/assets/icons/exclamation_circle.svg
  src/components/scenario/buttonGroup/buttonGroup.style.ts
  src/components/scenario/buttonGroup/buttonGroup.tsx
  src/components/scenario/characterHeader/characterHeader.style.ts
  src/components/scenario/characterHeader/characterHeader.tsx
  src/components/scenario/characterList/characterList.style.ts
  src/components/scenario/characterList/characterList.tsx
  src/components/scenario/checkBox/checkBox.tsx
  src/components/scenario/dropDown/dropDown.style.ts
  src/components/scenario/dropDown/dropDown.tsx
  src/components/scenario/scenarioItem/scenarioItem.style.ts
  src/components/scenario/scenarioItem/scenarioItem.tsx
  src/components/scenario/scenarioModal/scenarioModal.style.ts
  src/components/scenario/scenarioModal/scenarioModal.tsx
  src/pages/scenario/scenario.style.ts
  src/pages/scenario/scenario.tsx
  src/slices/scenarioSlice.ts
  src/store/store.ts
Labels: ✨ Feature

#77 [Feature/#75] 반응형 sidebar UI 구현
  src/components/common/sidebar/sidebar.style.ts
  src/components/common/sidebar/sidebar.tsx
Labels: ✨ Feature

#76 [Feature/#52] 로그인 상태 전역관리
  src/apis/auth/auth.ts
  src/apis/axiosInstance.ts
  src/main.tsx
  src/pages/auth/authHandler.tsx
  src/pages/login/login.tsx
  src/pages/signup/signup.tsx
  src/routes/index.tsx
  src/slices/authSlice.ts
  src/store/store.ts
Labels: ✨ Feature

#83 [Feature/#82] 사이드바 개선
  src/components/common/sidebar/sidebar.style.ts
  src/layouts/main/mainLayout.style.ts
Labels: ✨ Feature

#87 [Feature/#79] mypage 반응형 추가
  src/components/mypage/myProfile/MyProfile.style.ts
  src/components/mypage/myProfile/myProfile.tsx
  src/components/mypage/projectList/projectList.style.ts
  src/components/mypage/projectList/projectList.tsx
  src/components/mypage/projectNum/projectNum.style.ts
  src/pages/mypage/mypage.style.ts
Labels: ✨ Feature

#89 [Feature/#73] usersetting api 연결
  src/apis/auth/auth.ts
  src/apis/images/images.ts
  src/apis/mypage/mypage.ts
  src/apis/userController/userController.ts
  src/components/mypage/myProfile/myProfile.tsx
  src/hooks/images/useGetPresignedURL.ts
  src/hooks/images/useUploadPresignedURL.ts
  src/pages/userSetting/userSetting.tsx
  src/types/auth/auth.ts
Labels: ✨ Feature

#96 [Feature/#95] 필요없는 코드 삭제 및 수정
  src/components/auth/authInput/authInput.tsx
  src/components/auth/module/module.style.ts
  src/components/auth/module/module.tsx
  src/components/auth/validationMessage/validationMessage.style.ts
  src/components/auth/validationMessage/validationMessage.tsx
  src/components/common/input/input.style.ts
  src/components/common/input/validationMessage.tsx
  src/components/projectInfo/pageModal/pageModal.tsx
Labels: ✨ Feature

#99 [Feature/#98] 대시보드 api 정리
  src/apis/error/error.ts
  src/apis/test/test.ts
  src/constants/querykeys/queryKeys.ts
  src/enums/enums.ts
  src/hooks/error/useGetError.ts
  src/hooks/test/useGetStatistics.ts
  src/hooks/test/usePaginateSearchTestList.ts
  src/hooks/test/usePaginateTestList.ts
  src/types/error/error.ts
  src/types/test/test.ts
Labels: ✨ Feature

#101 [Feature/#60] select 컴포넌트 생성
  src/components/dashboard/selectBox/selectBox.style.ts
  src/components/dashboard/selectBox/selectBox.tsx
  src/components/dashboard/table/table.style.ts
  src/components/dashboard/table/table.tsx
  src/constants/state/state.ts
  src/mocks/tableData.ts
  src/styles/global.ts
Labels: ✨ Feature

#103 [Feature/#100] 시나리오 조회 아이콘 수정, 선택 기능 추가
  src/components/scenario/buttonGroup/buttonGroup.tsx
  src/components/scenario/characterHeader/characterHeader.style.ts
  src/components/scenario/characterHeader/characterHeader.tsx
  src/components/scenario/characterList/characterList.tsx
  src/components/scenario/dropDown/dropDown.tsx
  src/components/scenario/scenarioItem/scenarioItem.style.ts
  src/components/scenario/scenarioItem/scenarioItem.tsx
  src/routes/index.tsx
  src/slices/scenarioSlice.ts
Labels: ✨ Feature

#93 [Feature/#72] 마이페이지 API 연결
  src/apis/mypage/mypage.ts
  src/apis/userController/userController.ts
  src/assets/icons/arrow_left_noColor.svg
  src/assets/icons/arrow_right_noColor.svg
  src/components/auth/socialLogo/socialLogo.tsx
  src/components/mypage/myProfile/MyProfile.style.ts
  src/components/mypage/myProfile/myProfile.tsx
  src/components/mypage/project/project.tsx
  src/components/mypage/projectList/projectList.style.ts
  src/components/mypage/projectList/projectList.tsx
  src/constants/querykeys/queryKeys.ts
  src/enums/enums.ts
  src/hooks/mypage/useGetUserInfo.ts
  src/hooks/userController/userController.ts
  src/types/mypage/mypage.ts
  src/types/userController/userController.ts
  src/utils/findUnlinkedSocials.ts
Labels: ✨ Feature

#97 [Feature/#94] findingPassword API 연결
  src/apis/auth/auth.ts
  src/components/findingPassword/findingPasswordStep.style.ts
  src/components/findingPassword/findingPasswordStep1.tsx
  src/components/findingPassword/findingPasswordStep2.tsx
  src/hooks/auth/useChangePassword.ts
  src/hooks/common/customQuery.ts
  src/pages/findingPassword/findingPassword.tsx
  src/types/auth/auth.ts
Labels: ✨ Feature

#105 [Feature/#54] 달력 컴포넌트 생성
  package.json
  pnpm-lock.yaml
  src/components/dashboard/calendar/calendar.style.ts
  src/components/dashboard/calendar/calendar.tsx
  src/components/dashboard/table/table.tsx
  src/constants/day/day.ts
  src/slices/calendarSlice.ts
  src/store/store.ts
  src/utils/getDayList.ts
Labels: ✨ Feature

#108 [Feature/#102] 로그인 response 변경에 따른 수정 및 프로필 사진, 닉네임 전역에서 관리
  src/apis/auth/auth.ts
  src/components/auth/socialLogo/socialLogo.tsx
  src/components/common/sidebar/sidebar.tsx
  src/constants/querykeys/queryKeys.ts
  src/hooks/auth/useGetOAuth.ts
  src/pages/auth/authHandler.tsx
  src/pages/auth/basicOAuth.tsx
  src/pages/auth/githubOAuth.tsx
  src/pages/auth/googleOAuth.tsx
  src/pages/auth/kakaoOAuth.tsx
  src/pages/login/login.tsx
  src/pages/signup/signup.tsx
  src/routes/index.tsx
  src/slices/authSlice.ts
  src/types/auth/auth.ts
Labels: ✨ Feature

#109 [Feature/#107] 훅 분리하기
  src/apis/images/images.ts
  src/components/auth/module/module.style.ts
  src/components/auth/module/module.tsx
  src/components/common/sidebar/logtoutModal/logoutModal.tsx
  src/components/findingPassword/findingPasswordStep1.tsx
  src/components/mypage/myProfile/myProfile.tsx
  src/components/mypage/projectList/projectList.style.ts
  src/components/mypage/projectList/projectList.tsx
  src/components/mypage/projectNum/projectNum.tsx
  src/hooks/auth/useChangePassword.ts
  src/hooks/auth/useUserAuth.ts
  src/hooks/common/useCustomMutation.ts
  src/hooks/images/useGetPresignedURL.ts
  src/hooks/images/useImage.ts
  src/hooks/images/useUploadPresignedURL.ts
  src/hooks/mypage/useGetUserInfo.ts
  src/hooks/mypage/useUserInfo.ts
  src/hooks/project/useProject.ts
  src/pages/findingPassword/findingPassword.tsx
  src/pages/login/login.tsx
  src/pages/mypage/mypage.tsx
  src/pages/signup/signup.tsx
  src/pages/userSetting/userSetting.tsx
  src/slices/authSlice.ts
  src/types/images/images.ts
Labels: ✨ Feature

#114 🐞 [BugFix] 회원가입 후 프로필 세팅 오류 수정
  src/pages/signup/signup.tsx
Labels: 🐞 BugFix

#117 [Feature/#115] 인풋 thin 타입 추가
  src/components/common/input/input.style.ts
  src/components/common/input/input.tsx
Labels: ✨ Feature

#118 ✨ [Feature] 테스트 통계 조회 api 연결
  src/apis/test/test.ts
  src/components/dashboard/projectInfoBox/projectInfoBox.tsx
  src/components/dashboard/projectStatistics/projectStatistics.style.ts
  src/components/dashboard/projectStatistics/projectStatistics.tsx
  src/pages/dashboard/dashboard.style.ts
  src/pages/dashboard/dashboard.tsx
  src/types/test/test.ts
Labels: ✨ Feature

#119 [Feature/#111] 사이드바 api 연결 1차
  src/apis/sidebar/sidebar.ts
  src/components/common/sidebar/projectModal/projectModal.style.ts
  src/components/common/sidebar/projectModal/projectModal.tsx
  src/components/common/sidebar/sidebar.tsx
  src/constants/querykeys/queryKeys.ts
  src/hooks/sidebar/sidebar.ts
  src/hooks/sidebar/useGetTeamMember.ts
  src/types/sidebar/sidebar.ts
Labels: ✨ Feature

#123 [Feature/#110] 일반로그인 에러 해결, https로 변경
  .github/workflows/main.yaml
  .gitignore
  package.json
  src/apis/auth/auth.ts
  src/apis/axiosInstance.ts
  src/apis/sidebar/sidebar.ts
  src/apis/userController/userController.ts
  src/components/auth/socialLogo/socialLogo.tsx
  src/components/common/sidebar/sidebar.tsx
  src/components/mypage/myProfile/myProfile.tsx
  src/constants/querykeys/queryKeys.ts
  src/hooks/auth/useGetOAuth.ts
  src/hooks/auth/useUserAuth.ts
  src/hooks/sidebar/sidebar.ts
  src/main.tsx
  src/pages/authHandler/authHandler.tsx
  src/pages/login/login.tsx
  src/pages/loginRedirect/loginRedirect.tsx
  src/pages/signup/signup.tsx
  src/pages/userSetting/userSetting.tsx
  src/routes/index.tsx
  src/slices/authSlice.ts
  src/types/auth/auth.ts
  src/types/sidebar/sidebar.ts
  src/utils/cookies.ts
  vite.config.ts
Labels: ✨ Feature

#126 [Feature/#125] 소셜로그인, 일반 로그인 쿠키 방식으로 변경
  src/apis/axiosInstance.ts
  src/pages/login/login.tsx
  src/pages/loginRedirect/loginRedirect.tsx
  src/pages/signup/signup.tsx
  src/slices/authSlice.ts
Labels: ✨ Feature

#128 [Feature/#127] 로그인 리팩토링
  package.json
  pnpm-lock.yaml
  src/apis/axiosInstance.ts
  src/components/auth/socialLogo/socialLogo.tsx
  src/components/mypage/failModal/failModal.style.ts
  src/components/mypage/failModal/failModal.tsx
  src/main.tsx
  src/pages/authHandler/authHandler.tsx
  src/pages/login/login.style.ts
  src/pages/login/login.tsx
  src/pages/loginRedirect/loginRedirect.tsx
  src/pages/signup/signup.tsx
  src/pages/userSetting/userSetting.tsx
  src/routes/index.tsx
  src/slices/authSlice.ts
  src/store/store.ts
  src/types/auth/auth.ts
  src/utils/cookies.ts
Labels: ♻️ Refactor

#131 🐞 [BugFix] 로그인 무한 리렌더링 수정
  src/components/common/sidebar/sidebar.tsx
  src/hooks/sidebar/sidebar.ts
  src/pages/login/login.tsx
  src/pages/loginRedirect/loginRedirect.tsx
Labels: 🐞 BugFix

#132 [Feature/#129] 윈도우 세팅
  package.json
  pnpm-lock.yaml
Labels: ⚙️ Setting

#134 [Feature/#133] 로그인 Response 변경에 따른 수정
  src/pages/login/login.tsx
  src/pages/userSetting/userSetting.tsx
  src/types/auth/auth.ts
Labels: ♻️ Refactor

#135 [Feature/#120] 사이드바 API 연결
  src/components/common/sidebar/projectModal/projectModal.style.ts
  src/components/common/sidebar/projectModal/projectModal.tsx
  src/components/common/sidebar/sidebar.style.ts
  src/components/common/sidebar/sidebar.tsx
Labels: ✨ Feature

#137 [Feature/#136] tooltip 구현
  src/components/projectInfo/toolTip/toolTip.style.ts
  src/components/projectInfo/toolTip/toolTip.tsx
  src/pages/projectInfo/projectInfo.style.ts
  src/pages/projectInfo/projectInfo.tsx
Labels: ✨ Feature

#145 ✨ [Feature] 대시보드 에러박스 크기 수정
  src/components/dashboard/projectInfoBox/projectInfoBox.style.ts
  src/components/dashboard/projectStatistics/projectStatistics.style.ts
  src/pages/dashboard/dashboard.style.ts
Labels: ✨ Feature

#150 [Feature/#149] 에러 해결
  src/pages/userSetting/userSetting.tsx
Labels: 🐞 BugFix

#151 [Feature/#146] UI 수정
  src/assets/icons/book.svg
  src/assets/icons/branch_white.svg
  src/assets/icons/crown.svg
  src/assets/icons/files.svg
  src/assets/icons/page.svg
  src/assets/icons/shield.svg
  src/pages/projectInfo/projectInfo.style.ts
  src/pages/projectInfo/projectInfo.tsx
Labels: ✨ Feature

#142 [Feature/#140] 프로젝트 모달 수정
  src/components/common/sidebar/projectModal/projectModal.style.ts
  src/components/common/sidebar/projectModal/projectModal.tsx
  src/components/common/sidebar/sidebar.style.ts
Labels: ✨ Feature

#152 [Feature/#138] zip API 연결
  src/apis/projectInfo/projectInfo.ts
  src/apis/projectInfo/uploadZipFile.ts
  src/components/projectInfo/pageModal/pageModal.style.ts
  src/components/projectInfo/pageModal/pageModal.tsx
  src/constants/querykeys/queryKeys.ts
  src/hooks/projectInfo/useProjectInfo.ts
  src/hooks/projectInfo/useUploadZip.ts
  src/pages/addProject/addProject.style.ts
  src/pages/addProject/addProject.tsx
  src/pages/projectInfo/projectInfo.style.ts
  src/pages/projectInfo/projectInfo.tsx
  src/routes/index.tsx
  src/types/projectInfo/projectInfo.ts
Labels: ✨ Feature

#155 [Refactor/#154] 버튼 UI 업데이트
  src/components/common/button/button.style.ts
Labels: ♻️ Refactor

#156 [Feature/#153] Introduce 수정 API 연결
  src/apis/projectInfo/projectInfo.ts
  src/components/projectInfo/characterModal/characterModal.style.ts
  src/components/projectInfo/characterModal/characterModal.tsx
  src/components/projectInfo/inviteModal/inviteModal.style.ts
  src/components/projectInfo/inviteModal/inviteModal.tsx
  src/components/projectInfo/pageModal/pageModal.style.ts
  src/components/projectInfo/pageModal/pageModal.tsx
  src/hooks/projectInfo/useProjectInfo.ts
  src/pages/projectInfo/projectInfo.style.ts
  src/pages/projectInfo/projectInfo.tsx
  src/types/projectInfo/projectInfo.ts
Labels: ✨ Feature

#148 ✨ [Feature] 로딩 컴포넌트 구현
  package.json
  pnpm-lock.yaml
  src/assets/lotties/Loading.json
  src/components/common/loading/loading.style.ts
  src/components/common/loading/loading.tsx
  src/components/common/modalProvider/modalProvider.tsx
  src/components/dashboard/projectStatistics/projectStatistics.tsx
  src/components/projectInfo/inviteModal/inviteModal.tsx
  src/pages/dashboard/dashboard.tsx
  src/slices/modalSlice.ts
Labels: ✨ Feature

#160 ✨ [Feature] 테스트 리스트 조회 api 연결
  src/apis/test/test.ts
  src/components/dashboard/selectBox/selectBox.tsx
  src/components/dashboard/table/pageNameHeader.tsx
  src/components/dashboard/table/stateHeader.tsx
  src/components/dashboard/table/table.style.ts
  src/components/dashboard/table/table.tsx
  src/constants/querykeys/queryKeys.ts
  src/constants/state/state.ts
  src/hooks/test/usePaginateSearchTestList.ts
  src/hooks/test/usePaginateTestList.ts
  src/mocks/tableData.ts
  src/types/test/test.ts
Labels: ✨ Feature

#165 [Feature/#161] 시나리오 조회 UI 수정
  src/components/common/projectTitle/projectTitle.style.ts
  src/components/common/projectTitle/projectTitle.tsx
  src/components/scenario/characterHeader/characterHeader.style.ts
  src/components/scenario/characterHeader/characterHeader.tsx
  src/components/scenario/scenarioItem/scenarioItem.style.ts
  src/components/scenario/scenarioItem/scenarioItem.tsx
  src/components/scenario/scenarioModal/scenarioModal.style.ts
  src/components/scenario/scenarioModal/scenarioModal.tsx
  src/pages/scenario/scenario.style.ts
  src/slices/scenarioSlice.ts
Labels: ✨ Feature

#166 ✨ [Feature] 에러보드 api 연결
  src/apis/error/error.ts
  src/components/common/modal/modal.style.ts
  src/components/dashboard/errorModal/errorModal.style.ts
  src/components/dashboard/errorModal/errorModal.tsx
  src/components/dashboard/table/table.tsx
  src/components/scenario/scenarioModal/scenarioModal.tsx
  src/slices/modalSlice.ts
  src/styles/global.ts
Labels: ✨ Feature

#167 [Feature/#159] 팀원 초대 API 연결
  src/apis/projectInfo/projectInfo.ts
  src/components/common/button/button.style.ts
  src/components/common/sidebar/projectModal/projectModal.tsx
  src/components/common/sidebar/sidebar.style.ts
  src/components/common/sidebar/sidebar.tsx
  src/components/projectInfo/inviteModal/inviteModal.tsx
  src/hooks/projectInfo/useInviteMember.ts
  src/hooks/projectInfo/useProjectInfo.ts
  src/pages/addProject/addProject.tsx
  src/pages/projectInfo/projectInfo.tsx
  src/types/projectInfo/projectInfo.ts
Labels: ✨ Feature

#172 [Fix/#171] navigate 오류 해결
  src/pages/addProject/addProject.tsx
Labels: 🐞 BugFix

#173 [Feature/#170] 페이지 생성 API 연결
  src/apis/projectInfo/projectInfo.ts
  src/components/projectInfo/pageModal/pageModal.style.ts
  src/components/projectInfo/pageModal/pageModal.tsx
  src/components/projectInfo/toolTip/toolTip.tsx
  src/constants/querykeys/queryKeys.ts
  src/hooks/projectInfo/useAddPage.ts
  src/hooks/projectInfo/useGetScenario.ts
  src/hooks/projectInfo/useProjectInfo.ts
  src/pages/projectInfo/projectInfo.style.ts
  src/pages/projectInfo/projectInfo.tsx
  src/pages/projectInfo/projectStructure.style.ts
  src/pages/projectInfo/projectStructure.tsx
  src/types/projectInfo/projectInfo.ts
Labels: ✨ Feature

#169 [Feature/#163] 로그아웃, 리프레시 api 연결
  src/apis/auth/auth.ts
  src/apis/axiosInstance.ts
  src/components/common/sidebar/logtoutModal/logoutModal.tsx
  src/slices/authSlice.ts
Labels: ✨ Feature

#178 [Feature/#170] UI 수정 및 API 연결
  src/apis/projectInfo/projectInfo.ts
  src/components/projectInfo/characterModal/characterModal.tsx
  src/components/projectInfo/toolTip/toolTip.tsx
  src/constants/querykeys/queryKeys.ts
  src/hooks/projectInfo/useProjectInfo.ts
  src/pages/projectInfo/projectInfo.style.ts
  src/pages/projectInfo/projectInfo.tsx
  src/pages/projectInfo/projectStructure.style.ts
  src/pages/projectInfo/projectStructure.tsx
  src/types/projectInfo/projectInfo.ts
Labels: ✨ Feature
